### ISSUE TITLE
error: ‘getContextPlatformVersion’ is not a member of ‘cl::detail’ in some cases

### ISSUE THREAD

**Issue by TSlivede** [KhronosGroup/OpenCL-CLHPP#108]
I got the error `error: ‘getContextPlatformVersion’ is not a member of ‘cl::detail’` when building my project:

It seems that on line [7078](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L7075-L7078) (and [7144](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L7141-L7144), [7209](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L7206-L7209), [7276](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L7273-L7276), [7327](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L7324-L7327) and [7378](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L7375-L7378)) `getContextPlatformVersion` is used in a `#if`-block that is enabled if `CL_HPP_MINIMUM_OPENCL_VERSION`  is less than 200:
```
#if CL_HPP_TARGET_OPENCL_VERSION >= 200 && CL_HPP_MINIMUM_OPENCL_VERSION < 200
            // Run-time decision based on the actual platform
            {
                cl_uint version = detail::getContextPlatformVersion(context());
```

However, the (only) definition of `getContextPlatformVersion` (on line [1738](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L1738)) is only active if `CL_HPP_MINIMUM_OPENCL_VERSION` is less than 120 (checked at line [1700](https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl2.hpp#L1700)):
```
#if CL_HPP_TARGET_OPENCL_VERSION >= 120 && CL_HPP_MINIMUM_OPENCL_VERSION < 120
```
The error should therefore always ocure if `CL_HPP_TARGET_OPENCL_VERSION` is 200 and `CL_HPP_MINIMUM_OPENCL_VERSION` is 120.

I could complile my project by changing that line (1700) to this:
```
#if CL_HPP_TARGET_OPENCL_VERSION >= 120 && CL_HPP_MINIMUM_OPENCL_VERSION < 200
```
But I don't know if that is the proper solution or if that would have other side effects, therefore I didn't create a pull request and instead created this issue...

**Comment by bashbaug** [comment]
I think your proposed fix is fine, but I wonder if the checks around `getContextPlatformVersion` could be removed outright vs. expanded since it doesn't look like it uses any newer OpenCL functionality.

@jrprice , do you have any input?  It looks like you were involved in the PR that added these checks: https://github.com/KhronosGroup/OpenCL-CLHPP/pull/14#issuecomment-227499245.  Thanks!

**Comment by sudden6** [comment]
Hi, I'm hitting the same problem, is there a fix already in master?

**Comment by bashbaug** [comment]
It doesn't look like this has been fixed yet.

@jrprice do you have a preferred fix?  It looks like we could:

* Change the guards around the definitions of these functions to `CL_HPP_MINIMUM_OPENCL_VERSION < 200`, as described above, which will work for the current usage.
* Remove the guards entirely so these functions are available regardless of the target and minimum versions, just in case additional usages are added in the future.

**Comment by jrprice** [comment]
Sorry for taking so long to look at this.

> Remove the guards entirely so these functions are available regardless of the target and minimum versions

I can't think of a reason to keep them, so I'd vote for this fix.

**Comment by sudden6** [comment]
Although the header file has been moved, this is still not fixed.

**Comment by bashbaug** [comment]
Looking through old issues I thought this might have been fixed, but it looks like we still have a problem.

The guard for `getContextPlatformVersion` is still:

```c
#if CL_HPP_TARGET_OPENCL_VERSION >= 120 && CL_HPP_MINIMUM_OPENCL_VERSION < 120
```

But some of the places where it is used is guarded by:

```c
#if CL_HPP_TARGET_OPENCL_VERSION >= 200 && CL_HPP_MINIMUM_OPENCL_VERSION < 200
```

This means we'll generate an error when `CL_HPP_TARGET_OPENCL_VERSION` is `>= 200` and `CL_HPP_MINIMUM_OPENCL_VERSION` is `< 200` and `>= 120`.... which is super unfortunate since I think a common build configuration will be to target OpenCL 3.0 but support OpenCL 1.2.

We should fix this.  If we don't want to remove the guards around `getContextPlatformVersion` entirely, I think we could change the guard for it to be `< 200` also and it'd work:

```c
#if CL_HPP_TARGET_OPENCL_VERSION >= 120 && CL_HPP_MINIMUM_OPENCL_VERSION < 120
```
